[package]
name = "ysos_kernel"
version = "0.3.0"
edition = "2021"
<<<<<<< HEAD
authors = ["GZTime <Time.GZ@outlook.com>"]
=======
>>>>>>> 5e6e567754b757eb2bb7dc4d28e2a848efc12ef4
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boot = { package = "ysos_boot", path = "../boot", default-features = false }
<<<<<<< HEAD
elf = { package = "ysos_elf", path = "../elf" }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
=======
lazy_static = { version = "1.4", features = ["spin_no_std"] }
crossbeam-queue = { version = "0.3", default-features = false, features = ["alloc"] }
>>>>>>> 5e6e567754b757eb2bb7dc4d28e2a848efc12ef4
paste = "1.0"
spin = "0.9"
x86 = "0.52"
x86_64 = "0.14"
log = "0.4"
<<<<<<< HEAD
bit_field = "0.10"
micromath = { version = "2.0", features = ["num-traits"] }
bitflags = "2.3"
chrono = { version = "0.4", default-features = false }
libm = "0.2"
linked_list_allocator = "0.10"
pc-keyboard = "0.7"
crossbeam-queue = { version = "0.3", default-features = false, features = ["alloc"] }
volatile = "0.5"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
=======
bitflags = "2.3"
bit_field = "0.10"
libm = "0.2"
linked_list_allocator = "0.10"
volatile = "0.5"
>>>>>>> 5e6e567754b757eb2bb7dc4d28e2a848efc12ef4
